n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?',n.isnumeric())
print('É uma letra?', n.isalpha())
print('Esta so com letras maiusculas?', n.isupper())
print('esta so com letars minusculas?', n.islower())
print('Esta so com a primeira letra maiuscula?', n.istitle())
print('Letra e numero?', n.isalnum())