from random import randint
a = randint(0, 10)
b = randint(0, 10)
c = randint(0, 10)
d = randint(0, 10)
e = randint(0, 10)
tupla = (a, b , c , d , e)
print(f'O progama gerou: {tupla} ')
print(f'O maior numero foi: {max(tupla)}')
print(f'O menor numero foi: {min(tupla)}')